services:
    ssl-cert-updater:
        image: git.tkoessler.de/timokoessler/ssl-cert-updater:latest
        restart: always
        container_name: ssl-cert-updater
        volumes:
            - ./config:/home/node/config
        ports:
            - '127.0.0.1:8081:3000'
            - '{PUBLIC_IP}:53:5333/udp'
