name: Docker
env:
    NODE_VERSION: '20'
on:
    push:
        branches:
            - 'main'
jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - uses: actions/checkout@v3
            - name: Cache
              uses: actions/cache@v3
              with:
                  path: |
                      .turbo/
                      node_modules/.cache/
                      backend/.turbo/
                      frontend/.turbo/
                      client/.turbo/
                      ~/.pkg-cache/
                  key: ${{ runner.os }}-${{env.NODE_VERSION}}-cache-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-${{env.NODE_VERSION}}-cache-
            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: ${{env.NODE_VERSION}}
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Container Registry
              uses: docker/login-action@v2
              with:
                  registry: git.tkoessler.de
                  username: ${{ secrets.RegistryUser }}
                  password: ${{ secrets.RegistryPass }}
            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  push: true
                  platforms: linux/amd64
                  file: ./Dockerfile.github
                  context: .
                  tags: git.tkoessler.de/timokoessler/ssl-cert-updater-next:latest
                  cache-from: type=registry,ref=git.tkoessler.de/timokoessler/ssl-cert-updater-next:latest
                  cache-to: type=inline
